Put new HSQLDB script in trunk (references #448)

diff --git a/bin/hsqldb b/bin/hsqldb
--- a/bin/hsqldb
+++ b/bin/hsqldb
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 #
@@ -45,39 +45,63 @@
 #   Jonathan Clarke <jon@lsc-project.org>
 #   Remy-Christophe Schermesser <rcs@lsc-project.org>
 #
-# ---------------------------------------------------------------------------------
-#
-# Version 0.1 (2009):
-# - First version
-# Author: Thomas CHEMINEAU
-#
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+
+# work out where LSC lives
+LSC_HOME=$(dirname "${BASH_SOURCE}")/..
+if [ ${LSC_HOME:0:1} != "/" ] ; then
+        LSC_HOME="${PWD}/${LSC_HOME}"
+fi
 
 # ---------------------------------------------------------------------------------
 # CONFIGURATION
 # ---------------------------------------------------------------------------------
 
-# LSC home directory
-LSC_HOME=/usr/local/lsc
+# LSC directories
+CFG_DIR="$LSC_HOME/etc"
+LIB_DIR="$LSC_HOME/lib"
+LOG_DIR="/tmp"
+LOG_FILE="$LOG_DIR/hsqldb.log"
+VAR_DIR="$LSC_HOME/var"
+
 # HSQLDB jar file
-HSQLDB_LIB=$LSC_HOME/lib/hsqldb*.jar
+HSQLDB_LIB=$LIB_DIR/hsqldb*.jar
+
 # Temporary directory so that HSQLDB server could store files
-HSQLDB_DIR=$LSC_HOME/var/hsqldb
+HSQLDB_DIR=$VAR_DIR/hsqldb
+
 # HSQLDB server PID file
-HSQLDB_PIDFILE=$LSC_HOME/var/hsqldb.pid
+HSQLDB_PIDFILE=$VAR_DIR/hsqldb.pid
+
+# Table name
+HSQLDB_TABLE=csvdata
+
 # Default CSV separator
 CSV_SEPARATOR=";"
 
 # ---------------------------------------------------------------------------------
 # FUNCTIONS
 # ---------------------------------------------------------------------------------
+function log() {
+  echo "$(date "+${DATE_FORMAT:-%Y/%m/%d %T}") [hsqldb] $1" >> "$LOG_FILE"
+}
+
+function fatal() {
+  log $1
+  echo "$(date "+${DATE_FORMAT:-%Y/%m/%d %T}") [hsqldb] $1" 1>&2
+}
 
 #
 # Drop all data from the HSQLDB instance.
 #
 data_drop()
 {
-  hsqldb_sqlQuery "DROP TABLE csvdata" 2> /dev/null
+  hsqldb_sqlQuery "DROP TABLE $HSQLDB_TABLE;" 2> /dev/null
+  if [ $? -eq 0 ]; then
+    log "Table $HSQLDB_TABLE deleted"
+  else
+    fatal "Unable to delete table $HSQLDB_TABLE"
+  fi
 }
 
 #
@@ -101,19 +125,30 @@ data_import()
   done
   IFS=$IOFS
   if [ -n "$HSQLDB_TABLEDEF" ]; then
-    hsqldb_sqlQuery "CREATE TEXT TABLE csvdata ($HSQLDB_TABLEDEF)"
+    hsqldb_sqlQuery "CREATE TEXT TABLE $HSQLDB_TABLE ($HSQLDB_TABLEDEF);"
     if [ $? -eq 0 ]; then
+      log "Table $HSQLDB_TABLE created"
       nblines=`cat $1 | wc -l`
       let nblines--
       tail -n $nblines $1 > $HSQLDB_DIR/`basename $1`
       sep=`hsqldb_checkCsvSeparator $2`
-      hsqldb_sqlQuery "SET TABLE csvdata SOURCE \"`basename $1`;fs=$sep\"" > /dev/null 2>&1
-      echo $?
+      encoding=`file $1  2> /dev/null | cut -d' ' -f2`
+      if [ "x$encoding" == "xUTF-8" ] ; then
+        hsqldb_sqlQuery "SET TABLE $HSQLDB_TABLE SOURCE \"`basename $1`;fs=$sep;encoding=UTF-8\";" > /dev/null 2>&1
+      else
+        hsqldb_sqlQuery "SET TABLE $HSQLDB_TABLE SOURCE \"`basename $1`;fs=$sep\";" > /dev/null 2>&1
+      fi
+      if [ $? -eq 0 ]; then
+        log "File $1 imported into $HSQLDB_TABLE ($nblines rows)"
+	echo "$nblines lines imported into table $HSQLDB_TABLE"
+      else
+        fatal "Unable to import $1 into table $HSQLDB_TABLE"
+      fi
       rm -f $HSQLDB_DIR/`basename $1` > /dev/null 2>&1
       return
     fi
   fi
-  echo 1
+  exit 1
 }
 
 #
@@ -121,7 +156,7 @@ data_import()
 #
 data_show()
 {
-  hsqldb_sqlQuery "SELECT * FROM csvdata" 2> /dev/null
+  hsqldb_sqlQuery "SELECT * FROM $HSQLDB_TABLE;" 2> /dev/null
 }
 
 #
@@ -200,7 +235,7 @@ hsqldb_sqlQuery()
 hsqldb_startServer()
 {
   mkdir -p $HSQLDB_DIR
-  java -cp $LSC_HOME/lib/hsqldb*.jar org.hsqldb.Server \
+  java -cp $HSQLDB_LIB org.hsqldb.Server \
     -database.0 file:$HSQLDB_DIR/mydb -dbname.0 lscdb > /dev/null 2>&1 &
   echo $! > $HSQLDB_PIDFILE
   sleep 2
@@ -234,6 +269,11 @@ ACTIONS=""
 
 case "$1" in
   "--drop")
+    shift
+    if [ "$1" != "" ]; then
+      HSQLDB_TABLE="$1"
+      shift
+    fi
     ACTIONS="$ACTIONS dropdata"
     shift
     ;;
@@ -242,12 +282,21 @@ case "$1" in
     CSV_FILE="$1"
     shift
     if [ "$1" != "" ]; then
+      HSQLDB_TABLE="$1"
+      shift
+    fi
+    if [ "$1" != "" ]; then
       CSV_SEPARATOR="$1"
       shift
     fi
     ACTIONS="$ACTIONS importdata"
     ;;
   "--show")
+    shift
+    if [ "$1" != "" ]; then
+      HSQLDB_TABLE="$1"
+      shift
+    fi
     ACTIONS="$ACTIONS showdata"
     shift
     ;;
@@ -259,15 +308,21 @@ case "$1" in
     ACTIONS="$ACTIONS stopserver"
     shift
     ;;
+  "--status")
+    ACTIONS="$ACTIONS status"
+    shift
+    ;;
   "--help"|*)
     echo ""
     echo " $0 [<option>]"
     echo ""
     echo " One option from available options is:"
-    echo "   --import <file> [<separator>]    Import data from CSV file"
-    echo "   --show    Show data from database"
+    echo "   --import <file> [<table>] [<separator>]    Import data from CSV file"
+    echo "   --drop [<table>]   Drop data"
+    echo "   --show [<table>]   Show data from database"
     echo "   --start   Start the server"
     echo "   --stop    Stop the server"
+    echo "   --status  Display server status"
     echo "   --help    Print informations"
     echo ""
     exit 1
@@ -287,14 +342,14 @@ for action in $ACTIONS; do
       ;;
     "importdata")
       if [ ! -e "$CSV_FILE" ]; then
-        echo " Error - file '$1' not found"
+        echo " Error - file '$CSV_FILE' not found"
         exit 1
       fi
       if [ `hsqldb_checkInstance` -eq 1 ]; then
         echo " Error - server is not running"
         exit 1
       fi
-      exit `data_import "$CSV_FILE" "$CSV_SEPARATOR"`
+      data_import "$CSV_FILE" "$CSV_SEPARATOR"
       ;;
     "showdata")
       if [ `hsqldb_checkInstance` -eq 1 ]; then
@@ -317,6 +372,15 @@ for action in $ACTIONS; do
         hsqldb_cleanData
       fi
       ;;
+    "status")
+      if [ `hsqldb_checkInstance` -eq 0 ]; then
+        pid=`cat $HSQLDB_PIDFILE`
+	echo "HSQLDB Server is running (PID $pid)"
+        exit 0
+      else
+	echo "HSQLDB Server is not running"
+        exit 1
+      fi
 
   esac
 done
