Adding some output message

diff --git a/bin/lsc b/bin/lsc
--- a/bin/lsc
+++ b/bin/lsc
@@ -30,7 +30,10 @@
 #====================================================================
 # Changelog
 #====================================================================
-# Version 0.3 (01/2010à:
+# Version 0.4 (01/2010):
+# - Include a fatal error message in JAVA_HOME missing
+# - Notice log file location
+# Version 0.3 (01/2010):
 # - Update for LSC 1.2
 # - Guess the base directory for LSC and usual directories
 # - Use JAVA_HOME from the environment or java on PATH, without redefining it
@@ -68,6 +71,11 @@ function log() {
 	echo "$(date "+${DATE_FORMAT:-%Y/%m/%d %T}") [lsc] $1" >> "$LOG_FILE"
 }
 
+function fatal() {
+	log $1
+	echo "$(date "+${DATE_FORMAT:-%Y/%m/%d %T}") [lsc] $1" 1>&2
+}
+
 # Determine where the java exectuable is
 function get_java() {
 	# Do we have a JAVA_HOME environment variable?
@@ -81,14 +89,16 @@ function get_java() {
 	if [ $? -eq 0 ]; then return; fi
 
 	# Nothing seems approprite, warn and exit
-	log "No java executable found on PATH or in JAVA_HOME! Aborting."
-	log "Define JAVA_HOME or adjust your PATH variable to include java."
+	fatal "No java executable found on PATH or in JAVA_HOME! Aborting."
+	fatal "Define JAVA_HOME or adjust your PATH variable to include java."
 	exit 2
 }
 
 #====================================================================
 # Main
 #====================================================================
+
+echo "Messages are logged to $LOG_FILE"
 
 # check if we have java executable
 get_java
@@ -97,7 +107,7 @@ get_java
 if [ $(ps -efww | grep java | grep org.lsc | grep -v grep | wc -l) -ne 0 ] 
 then
 	# LSC already running
-	log "LSC already running - launch aborted"
+	fatal "LSC already running - launch aborted"
 
 	# since LSC already running, don't launch and exit
 	exit 1
@@ -113,10 +123,18 @@ do
 done
 
 cd "$CFG_DIR"
-${JAVA_COMMAND} -cp "$CLASSPATH" org.lsc.Launcher $*
+${JAVA_COMMAND} -cp "$CLASSPATH" org.lsc.Launcher $* &>> "$LOG_FILE"
+
+status=$?
 
 # LSC finished running
 log "LSC finished running"
+
+if [ $status -ne 0 ]
+then
+	echo "Last log file line: `tail -2 "$LOG_FILE" | head -1`" 1>&2
+	exit $status
+fi
 
 #====================================================================
 # Exit
