Merge commit 661 to trunk (Various updates to get the sample working. Includes a lib dir in sample dir, a tests JAR, a simple LDIF file for the sample. Fixes #174.)

diff --git a/sample/bin/lsc-sample b/sample/bin/lsc-sample
--- a/sample/bin/lsc-sample
+++ b/sample/bin/lsc-sample
@@ -71,7 +71,7 @@ if [ ${SAMPLE_HOME:0:1} != "/" ] ; then
 fi
 
 # HSQLDB jar file
-HSQLDB_LIB=$SAMPLE_HOME/../lib/hsqldb*.jar
+HSQLDB_LIB=$SAMPLE_HOME/lib/hsqldb*.jar
 # Temporary directory so that HSQLDB server could store files
 HSQLDB_DIR=/tmp/lsc/hsqldb
 # HSQLDB configuration file
@@ -188,6 +188,61 @@ hsqldb_sqlQuery()
   java -jar $HSQLDB_LIB --rcFile $HSQLDB_RC --sql "$1" lscdb
 }
 
+# Determine where the java exectuable is
+function get_java() {
+    # Do we have a JAVA_HOME environment variable?
+    if [ "z" != "z${JAVA_HOME}" ]; then
+        JAVA_COMMAND="${JAVA_HOME}/bin/java"
+        return
+    fi  
+
+    # Try java command on PATH as an alternative
+    JAVA_COMMAND="$(which java)"
+    if [ $? -eq 0 ]; then return; fi
+
+    # Nothing seems approprite, warn and exit
+    log "No java executable found on PATH or in JAVA_HOME! Aborting."
+    log "Define JAVA_HOME or adjust your PATH variable to include java."
+    exit 2
+}
+
+run_java_command()
+{
+	# check if we have java executable
+	get_java
+
+	for jar in "$SAMPLE_HOME"/../lib/*.jar; do
+		LDAPCP="$LDAPCP:$jar"
+	done
+
+	for jar in "$SAMPLE_HOME"/lib/*.jar; do
+		LDAPCP="$LDAPCP:$jar"
+	done
+
+	${JAVA_COMMAND} -cp "$LDAPCP" $1
+}
+
+start_ldap() {
+	echo "Starting LDAP server on ldap://localhost:33389/ ..."
+	run_java_command "org.lsc.utils.LdapServer -a -f $SAMPLE_HOME/etc"
+}
+
+stop_ldap() {
+	run_java_command "org.lsc.utils.LdapServer -o -f $SAMPLE_HOME/etc"
+}
+
+run() {
+	CLASSPATH=""
+	for jar in "$SAMPLE_HOME"/lib/*.jar; do
+		CLASSPATH="$CLASSPATH:$jar"
+	done
+	export CLASSPATH
+
+	command="$SAMPLE_HOME/../bin/lsc --config $SAMPLE_HOME/etc --synchronize all"
+	echo "Running $command"
+	$SAMPLE_HOME/../bin/lsc --config $SAMPLE_HOME/etc --synchronize all
+}
+
 # ---------------------------------------------------------------------------------
 # MAIN
 # ---------------------------------------------------------------------------------
@@ -215,6 +270,18 @@ case "$1" in
     ACTIONS="$ACTIONS showdata"
     shift
     ;;
+  "--start-ldap-server")
+    ACTIONS="$ACTIONS startldap"
+	shift
+	;;
+  "--stop-ldap-server")
+    ACTIONS="$ACTIONS stopldap"
+	shift
+	;;
+  "--run")
+	run
+	shift
+	;;
   "--clean")
 	ACTIONS="$ACTIONS cleandata"
 	shift
@@ -227,7 +294,9 @@ case "$1" in
     echo "   --import <file> [<separator>]    Import data from CSV file"
     echo "   --show    Show data from database"
     echo "   --drop    Drop the table $HSQLDB_TABLE from database"
-	echo "   --clean   Remove all files from disk"
+    echo "   --start-ldap-server    Launch an embedded OpenDS LDAP server"
+    echo "   --stop-ldap-server     Halt an embedded OpenDS LDAP server"
+    echo "   --run     Run the synchronization task"
 	echo "   --clean   Remove all files from disk"
     echo "   --help    Print informations"
     echo ""
@@ -252,8 +321,15 @@ for action in $ACTIONS; do
     "showdata")
       data_show
       ;;
+	"startldap")
+	  start_ldap
+	  ;;
+	"stopldap")
+	  stop_ldap
+	  ;;
     "cleandata")
       hsqldb_cleanData
+	  rm -rf /tmp/opends-test
       ;;
 
   esac
